class LiveCategory {
  final String id;
  final String name;
  final String icon; // Add icon property for visual appeal

  const LiveCategory({
    required this.id,
    required this.name,
    this.icon = '🎥', // Default icon
  });
}

const List<LiveCategory> kLiveCategories = [
  LiveCategory(id: '1', name: 'Gaming', icon: '🎮'),
  LiveCategory(id: '2', name: 'Music', icon: '🎵'),
  LiveCategory(id: '3', name: 'Lifestyle', icon: '💄'),
  LiveCategory(id: '4', name: 'Sports', icon: '⚽'),
  LiveCategory(id: '5', name: 'Talk Show', icon: '🎙️'),
  LiveCategory(id: '6', name: 'Education', icon: '📚'),
  LiveCategory(id: '7', name: 'Comedy', icon: '😂'),
  LiveCategory(id: '8', name: 'Cooking', icon: '🍳'),
  LiveCategory(id: '9', name: 'Travel', icon: '✈️'),
  LiveCategory(id: '10', name: 'Fitness', icon: '💪'),
  LiveCategory(id: '11', name: 'Art & Design', icon: '🎨'),
  LiveCategory(id: '12', name: 'Technology', icon: '💻'),
  LiveCategory(id: '13', name: 'Business', icon: '💼'),
  LiveCategory(id: '14', name: 'News', icon: '📰'),
  LiveCategory(id: '15', name: 'Entertainment', icon: '🎭'),
  LiveCategory(id: '16', name: 'ASMR', icon: '🔇'),
  LiveCategory(id: '17', name: 'Dance', icon: '💃'),
  LiveCategory(id: '18', name: 'Fashion', icon: '👗'),
  LiveCategory(id: '19', name: 'Beauty', icon: '💅'),
  LiveCategory(id: '20', name: 'DIY & Crafts', icon: '🛠️'),
  LiveCategory(id: '21', name: 'Science', icon: '🔬'),
  LiveCategory(id: '22', name: 'Gaming Mobile', icon: '📱'),
  LiveCategory(id: '23', name: 'Gaming PC', icon: '🖥️'),
  LiveCategory(id: '24', name: 'Gaming Console', icon: '🎮'),
  LiveCategory(id: '25', name: 'Music Production', icon: '🎹'),
  LiveCategory(id: '26', name: 'Singing', icon: '🎤'),
  LiveCategory(id: '27', name: 'DJ & Mixing', icon: '🎧'),
  LiveCategory(id: '28', name: 'Podcast', icon: '🎙️'),
  LiveCategory(id: '29', name: 'Q&A', icon: '❓'),
  LiveCategory(id: '30', name: 'Interview', icon: '🎯'),
  LiveCategory(id: '31', name: 'Meditation', icon: '🧘'),
  LiveCategory(id: '32', name: 'Yoga', icon: '🧘‍♀️'),
  LiveCategory(id: '33', name: 'Motivation', icon: '🚀'),
  LiveCategory(id: '34', name: 'Finance', icon: '💰'),
  LiveCategory(id: '35', name: 'Crypto', icon: '₿'),
  LiveCategory(id: '36', name: 'Gaming: FPS', icon: '🔫'),
  LiveCategory(id: '37', name: 'Gaming: MOBA', icon: '⚔️'),
  LiveCategory(id: '38', name: 'Gaming: RPG', icon: '⚔️'),
  LiveCategory(id: '39', name: 'Gaming: Strategy', icon: '♟️'),
  LiveCategory(id: '40', name: 'Gaming: Sports', icon: '🏈'),
  LiveCategory(id: '41', name: 'Music: Pop', icon: '🎵'),
  LiveCategory(id: '42', name: 'Music: Hip Hop', icon: '🎤'),
  LiveCategory(id: '43', name: 'Music: Rock', icon: '🎸'),
  LiveCategory(id: '44', name: 'Music: EDM', icon: '🎶'),
  LiveCategory(id: '45', name: 'Music: Jazz', icon: '🎷'),
  LiveCategory(id: '46', name: 'Food', icon: '🍕'),
  LiveCategory(id: '47', name: 'Baking', icon: '🍰'),
  LiveCategory(id: '48', name: 'Coffee & Tea', icon: '☕'),
  LiveCategory(id: '49', name: 'Wine Tasting', icon: '🍷'),
  LiveCategory(id: '50', name: 'Photography', icon: '📸'),
  LiveCategory(id: '51', name: 'Videography', icon: '🎥'),
  LiveCategory(id: '52', name: 'Gaming: Just Chatting', icon: '💬'),
  LiveCategory(id: '53', name: 'Gaming: Retro', icon: '🕹️'),
  LiveCategory(id: '54', name: 'Gaming: Indie', icon: '🎮'),
  LiveCategory(id: '55', name: 'Book Club', icon: '📖'),
  LiveCategory(id: '56', name: 'Movie Review', icon: '🎬'),
  LiveCategory(id: '57', name: 'TV Show Review', icon: '📺'),
  LiveCategory(id: '58', name: 'Anime & Manga', icon: '🎌'),
  LiveCategory(id: '59', name: 'Cosplay', icon: '👘'),
  LiveCategory(id: '60', name: 'Parenting', icon: '👶'),
  LiveCategory(id: '61', name: 'Relationships', icon: '💑'),
  LiveCategory(id: '62', name: 'Mental Health', icon: '🧠'),
  LiveCategory(id: '63', name: 'Study With Me', icon: '📝'),
  LiveCategory(id: '64', name: 'Language Learning', icon: '🗣️'),
  LiveCategory(id: '65', name: 'Coding Live', icon: '👨‍💻'),
  LiveCategory(id: '66', name: 'Design Live', icon: '🎨'),
  LiveCategory(id: '67', name: 'Gaming: Battle Royale', icon: '🎯'),
  LiveCategory(id: '68', name: 'Gaming: Racing', icon: '🏎️'),
  LiveCategory(id: '69', name: 'Gaming: Simulation', icon: '✈️'),
  LiveCategory(id: '70', name: 'Gaming: Fighting', icon: '🥊'),
  LiveCategory(id: '71', name: 'Gaming: Adventure', icon: '🗺️'),
  LiveCategory(id: '72', name: 'Gaming: Puzzle', icon: '🧩'),
  LiveCategory(id: '73', name: 'Music: Classical', icon: '🎻'),
  LiveCategory(id: '74', name: 'Music: Country', icon: '🤠'),
  LiveCategory(id: '75', name: 'Music: R&B', icon: '🎶'),
  LiveCategory(id: '76', name: 'Music: Soul', icon: '🎤'),
  LiveCategory(id: '77', name: 'Music: Reggae', icon: '🌴'),
  LiveCategory(id: '78', name: 'Music: Metal', icon: '🤘'),
  LiveCategory(id: '79', name: 'Street Food', icon: '🌮'),
  LiveCategory(id: '80', name: 'Vegan Cooking', icon: '🥬'),
  LiveCategory(id: '81', name: 'Mixology', icon: '🍹'),
  LiveCategory(id: '82', name: 'Skateboarding', icon: '🛹'),
  LiveCategory(id: '83', name: 'Surfing', icon: '🏄'),
  LiveCategory(id: '84', name: 'Snowboarding', icon: '🏂'),
  LiveCategory(id: '85', name: 'Basketball', icon: '🏀'),
  LiveCategory(id: '86', name: 'Soccer', icon: '⚽'),
  LiveCategory(id: '87', name: 'Tennis', icon: '🎾'),
  LiveCategory(id: '88', name: 'Golf', icon: '⛳'),
  LiveCategory(id: '89', name: 'Boxing', icon: '🥊'),
  LiveCategory(id: '90', name: 'MMA', icon: '🥋'),
  LiveCategory(id: '91', name: 'Esports', icon: '🏆'),
  LiveCategory(id: '92', name: 'Car Reviews', icon: '🚗'),
  LiveCategory(id: '93', name: 'Motorcycles', icon: '🏍️'),
  LiveCategory(id: '94', name: 'Cycling', icon: '🚴'),
  LiveCategory(id: '95', name: 'Running', icon: '🏃'),
  LiveCategory(id: '96', name: 'Swimming', icon: '🏊'),
  LiveCategory(id: '97', name: 'Gardening', icon: '🌻'),
  LiveCategory(id: '98', name: 'Home Improvement', icon: '🏠'),
  LiveCategory(id: '99', name: 'Interior Design', icon: '🛋️'),
  LiveCategory(id: '100', name: 'Pet Care', icon: '🐶'),
];
