// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg4EEa2u_BvzaUyp7c6HP7nJT-3HZP_fs',
    appId: '1:775545297921:ios:e7a01f24f4365f4f04f400',
    messagingSenderId: '775545297921',
    projectId: 'moonlightapp-12a0c',
    storageBucket: 'moonlightapp-12a0c.firebasestorage.app',
    iosBundleId: 'com.example.moonlight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtPmlV8UWGRH0i-BT1JPY6U6U3stKBShY',
    appId: '1:775545297921:web:c3802d91678299eb04f400',
    messagingSenderId: '775545297921',
    projectId: 'moonlightapp-12a0c',
    authDomain: 'moonlightapp-12a0c.firebaseapp.com',
    storageBucket: 'moonlightapp-12a0c.firebasestorage.app',
    measurementId: 'G-L95T9K2MHV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPmlV8UWGRH0i-BT1JPY6U6U3stKBShY',
    appId: '1:775545297921:web:c3802d91678299eb04f400',
    messagingSenderId: '775545297921',
    projectId: 'moonlightapp-12a0c',
    authDomain: 'moonlightapp-12a0c.firebaseapp.com',
    storageBucket: 'moonlightapp-12a0c.firebasestorage.app',
    measurementId: 'G-L95T9K2MHV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg4EEa2u_BvzaUyp7c6HP7nJT-3HZP_fs',
    appId: '1:775545297921:ios:e7a01f24f4365f4f04f400',
    messagingSenderId: '775545297921',
    projectId: 'moonlightapp-12a0c',
    storageBucket: 'moonlightapp-12a0c.firebasestorage.app',
    iosBundleId: 'com.example.moonlight',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwz8O_Yy08oRawA5g_0eN0FvtYvFzxluY',
    appId: '1:775545297921:android:5f5164ab27b08a6504f400',
    messagingSenderId: '775545297921',
    projectId: 'moonlightapp-12a0c',
    storageBucket: 'moonlightapp-12a0c.firebasestorage.app',
  );
}
